apiVersion: fleet.cattle.io/v1alpha1
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: fleet-default
  labels:
    streamx.com/cluster-role: ${CLUSTER_NAME}
    streamx.com/cluster-name: ${CLUSTER_NAME}
spec:
  kubeConfigSecret: ${CLUSTER_NAME}-kubeconfig