apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-pilot-services
  namespace: ${CLUSTER_NAME}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              streamx.com/worker-access: "true"